home/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^programs/$',views.programs, name='programs'),
    url(r'^team/$',views.team, name='team'),
    url(r'^about/$',views.about, name='about'),
    url(r'^student_signup/$',views.student_forms, name='student'),
    url(r'^teacher_signup/$',views.teacher_forms, name='teacher'),
]

tutortf/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]

home/models.py
from django.db import models

class student_form(models.Model):
	first_name=models.CharField(max_length=100)
	middle_name=models.CharField(max_length=100)
	last_name=models.CharField(max_length=100)
	birthday=models.DateField(max_length=50)
	gender=models.CharField(max_length=50)
	school=models.CharField(max_length=100)
	grade=models.IntegerField(max_length=1)
	email=models.EmailField()
	phone=models.IntegerField(max_length=12)
	program=models.CharField(max_length=50)


class teacher_form(models.Model):
	first_name=models.CharField(max_length=100)
	middle_name=models.CharField(max_length=100)
	last_name=models.CharField(max_length=100)
	birthday=models.DateField(max_length=50)
	gender=models.CharField(max_length=50)
	school=models.CharField(max_length=100)
	grade=models.IntegerField(max_length=1)
	email=models.EmailField()
	phone=models.IntegerField(max_length=12)
	program=models.CharField(max_length=50)
	reason=models.CharField(max_length=1000)
	qualifications=models.CharField(max_length=1000)
	methods=models.CharField(max_length=1000)

home/forms.py
from django import forms
from .models import student_form
from .models import teacher_form

GENDERS=(
	("Male", "Male"),
	("Female", "Female"),
	("Other", "Other"),
)

PROGRAMS=(
	("Tutoring","Tutoring"),
	("Debate","Debate"),
	("Programming","Programming"),
)

class student_form(forms.ModelForm):
	first_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	middle_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	birthday=forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
	gender=forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'choice'}),choices=GENDERS)
	school=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	grade=forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
	phone=forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	program=forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=PROGRAMS)

	class Meta:
		model=student_form
		fields=['first_name','middle_name','last_name','birthday','gender','school','grade','email','phone','program']

class teacher_form(forms.ModelForm):
	first_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	middle_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	last_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	birthday=forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control'}))
	gender=forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'choice'}),choices=GENDERS)
	school=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	grade=forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
	phone=forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
	program=forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,choices=PROGRAMS)
	reason=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}),label="Why do you want to tutor, teach debate, or teach programming?")
	qualifications=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}),label="What are you qualifications to tutor, teach debate, or teach programming?")
	methods=forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}),label="In your opinion, what is the best way for students to learn? How can you apply this while teaching in Tutoring the Future? ")

	class Meta:
		model=teacher_form

		fields=['first_name','middle_name','last_name','birthday','gender','school','grade','email','phone','program','reason','qualifications','methods']

home/views.py
from django.shortcuts import render,redirect
from .forms import student_form
from .forms import teacher_form

def home(request):
	return render(request,'home.html')

def programs(request):
	return render(request, 'programs.html')

def team(request):
	return render(request, 'team.html')

def about(request):
	return render(request, 'about.html')

def student_forms(request):

	if request.method == 'POST':
		form = student_form(request.POST)

		if form.is_valid():
			form.save(commit=False)
			first_name=form.cleaned_data.get('first_name')
			middle_name=form.cleaned_data.get('middle_name')
			last_name=form.cleaned_data.get('last_name')
			birthday=form.cleaned_data.get('birthday')
			gender=form.cleaned_data.get('gender')
			school=form.cleaned_data.get('school')
			grade=form.cleaned_data.get('grade')
			email=form.cleaned_data.get('email')
			phone=form.cleaned_data.get('phone')
			program=form.cleaned_data.get('program')

			form.save()
			return redirect('http://localhost:8000')
	else:
		form=student_form(request.POST)

	return render(request, 'student_signup.html', {'form': form})

def teacher_forms(request):

	if request.method == 'POST':
		form = teacher_form(request.POST)

		if form.is_valid():
			form.save(commit=False)
			first_name=form.cleaned_data.get('first_name')
			middle_name=form.cleaned_data.get('middle_name')
			last_name=form.cleaned_data.get('last_name')
			birthday=form.cleaned_data.get('birthday')
			gender=form.cleaned_data.get('gender')
			school=form.cleaned_data.get('school')
			grade=form.cleaned_data.get('grade')
			email=form.cleaned_data.get('email')
			phone=form.cleaned_data.get('phone')
			program=form.cleaned_data.get('program')
			reasons=form.cleaned_data.get('reasons')
			qualifications=form.cleaned_data.get('qualifications')
			methods=form.cleaned_data.get('methods')

			form.save();
			return redirect('http://localhost:8000')
	else:
		form=teacher_form(request.POST)

	return render(request, 'teacher_signup.html', {'form': form})

home/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style type="text/css">

</style>
{% endblock %}

{% block body %}
<div id="content-container" style="position:relative;top:15%;z-index:-1;width:95%;height:1400px;background-color: #D5D5D5;">
<div class="container">
<div class="row justify-content-md-center">

<div class="col-lg-5 col-md-auto">
<h1>About</h1>
<img src='{% static "images/shehbaz_headshot.jpg" %}' height="440px" width="400px">
</div>

<div class="col-lg-12" style="margin-top: 20px">
<p>“The future is in the hand of the next generation. This generation must power and develop the minds of the next generation.” Shehbaz Singh Virk.</p>
<p>I founded Tutoring the Future because I wanted students to have a greater opportunity to succeed. There is a ton of knowledge and variety of skills that are necessary for students to develop to succeed in the real world. I want students to be engaged in learning and be proficient in what they learn at school.</p>
<p>A lot of the time, school goes too fast for students, and they fall behind. Tutoring the Future provides students with the opportunity to clear up any misunderstandings and gain further insight into what they are learning. Speeding through lessons because the state requires it, does not mean the student will understand everything that is being taught. It is important to remember the big picture: students learn so they can apply concepts to those concepts to to the real world. Tutoring the Future allows students to master concepts, so they can apply them in the real world.</p>
<p>An essential part of life is communication. Your thoughts and ideas are worth much more when you can effectively verbalize them. Debate helps students analyze a variety of different topics, viewpoints, and the different perspectives that can be taken off a single statement. Through exposure to a wide range of different topics including economics, politics, philosophy, and much more students gain confidence and are able to better communicate their views and beliefs. </p>
<p>In the 21st century, it is becoming more and more important for students to be able to work with code. Programming is used in a variety of different fields and its applications are endless. Programming teaches students more than coding. Through programming many of students skills are enhanced. Their ability to analyze situations, recognize different situations, and problem solve tremendously increases. These essential skills are applicable to a multitude of fields.</p>
</div>

</div>
</div>

<footer id="footer">
<div style="padding:10px;">
<div style="float:right;padding:20px 80px 0 0">
  <a href="http://localhost:8000">Home</a><br />
  <a href="http://localhost:8000/programs/">Programs</a><br />
  <a href="http://localhost:8000/team">Team</a><br />
  <a href="http://localhost:8000/about">About</a><br />
  <br /><br />
  <a href="#">Back to the Top</a>
</div>
  <p style="color: white">Contact us:<br />someone@example.com</p>
  <p style="color: white">Website designed and mantained by: Yuvraj Virk</p>
  <br />
  <p style="color: white">©tutoringthefuture.com. All rights reserved.</p>
</div>
</footer>

</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
if($(window).height()/$(window).width()>1){
	var el9=$("#footer");
	var h=$("#content-container").height();
	el9.css("top",h-150+"px");
  
}else{
	var el9=$("#footer");
	var h=$("#content-container").height();
	el9.css("top",h-300+"px");
}

</script>
{% endblock %}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="http://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Rufina" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<style type="text/css">
    html, body{
        margin:0px;
        padding:0px;
        width:100%;
        height:100%;
        position:relative;
        z-index: 1000;
    }  
    .center{
        display: block;
        margin: 0 auto;
    }
    .nav-text{
        color:#808080;
        font-family: 'Rufina', serif;
        margin-right: 50px;
        font-weight: bold;
    }
    a:hover{
        color:#8C1A14;
        background-color:#f1f1f1;
    }
    .down{
        margin-top: 10px;
    }
    .active{
        color:#8C1A15;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

    /* Dropdown Content (Hidden by Default) */
    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        color:black;
    }

    /* Links inside the dropdown */
    .dropdown-content a {
        color:grey;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        font-size: 0.9em;
    }

    /* Change color of dropdown links on hover */
    .dropdown-content a:hover {background-color: #f1f1f1}

    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-content {
        display: block;
    }

    #content-container{
        position: relative;
        width:95%;
        margin-left: 2.5%;
        margin-top: 2%;
        background-color: #f1f1f1;
        padding: 10px;
    }
    #overlay-top{
        position: fixed;
        background-color: white;
        width: 100%;
        margin-top: -2%;
    }
    #overlay-bottom{
        position: fixed; 
        bottom: 0;
        background-color: white;
        width: 100%;
        height:5%;
    }
    .priority{
        z-index: 10000;
    }
    #footer{
        position:absolute;
        bottom:0;
        width:100%;
        height:100%;
        background-color:#9099A2;
        z-index:1000;
        color:white;
        height:300px;
        top:100px;
        left: 0;
    }
    h1{
        font-family: 'Merriweather', serif;
        color:#0789BB;
    }
</style>

{% block style %}
{% endblock %}
</head>

<body style="position:relative; z-index:999;">
<div id="overlay-top">
<img class="img-fluid center priority" src='{% static "images/ttf.png" %}' width="600px" height="200px">
 <nav class="navbar navbar-light navbar-toggleable-md ">

<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="margin-top: -50px">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="margin:0 auto;">
      <li class="nav-item">
        <a class="nav-link nav-text {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="http://localhost:8000">Home</a>
      </li>


      <div class="dropdown">
      <li class="nav-item-indent nav-item">
        <a class="nav-link nav-text dropbtn {% if request.resolver_match.url_name == 'programs' %}active{% endif %}" href="http://localhost:8000/programs/">Programs</a>
      </li>
      <div class="dropdown-content">
        <a href="http://localhost:8000/programs/#tutoring">Tutoring</a>
        <a href="http://localhost:8000/programs/#debate">Debate</a>
        <a href="http://localhost:8000/programs/#programming">Programming</a>
        <a href="http://localhost:8000/student_signup">Signup</a>
      </div>
      </div> 


      <div class="dropdown">
      <li class="nav-item-indent nav-item">
        <a class="nav-link dropbtn nav-text {% if request.resolver_match.url_name == 'team' %}active{% endif %}" href="http://localhost:8000/team/">Team</a>
      </li> 
       <div class="dropdown-content">
        <a href="http://localhost:8000/teacher_signup">Join us</a>
      </div>
      </div>

      <li class="nav-item-indent nav-item">
        <a class="nav-link dropbtn nav-text {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="http://localhost:8000/about">About</a>
      </li> 
      <!--
      <!--
      <div class="dropdown-content">
        <a href="#">Member Policy</a>
      </div>
      </div>
      -->
 
     </ul>
  </div>

</nav>
</div>

{% block body %}
{% endblock %}

<div id="overlay-bottom"></div>
</body>

{% block script %}
{% endblock %} 
</html>
    

home/templates/home.html
{% extends 'base.html' %}

{% block style %}
<style type="text/css">
	p{
		font-family: 'Roboto', sans-serif;
		font-size: 1em;
		color:black;
	}
	a:hover{
		text-decoration: none
		color:white;
		background-color: transparent;
	}
	h3{
		color:white;
	}
	.btn-lg, .btn-lg:visited {
    	color: #0789BB !important;
    	border-color: #0789BB;
	}
	.btn-lg:hover, .btn-lg :active{
		color: white !important;
    	border-color: #0789BB;
    	background-color: #0789BB;
	}
	.bm, .bm:visited {
    	color: white !important;
    	border-color: white;
	}
	.bm:hover, .bm :active{
		color: white !important;
    	border-color: #D5D5D5;
    	background-color: #D5D5D5;
	}
	.triangleLeft{
              width: 0;
              height: 0;
              border-top-width: 400px;
              border-top-style: solid;
              border-top-color: transparent;
              border-left-width: 1186px;
              border-left-style: solid;
              position: absolute;
              color:#6D7993;
              margin-left: -10px;
     }
     .triangleRight{
              width: 0;
              height: 0;
              border-bottom-width: 400px;
              border-bottom-style: solid;
              border-bottom-color: transparent;
              border-right-width: 1187px;
              border-right-style: solid;
              position: absolute;
              color:#D5D5D5;
              margin-left: -10px;
     }
     .box1{
     	width: 100%;
     	height: 110%;
        background-color:#6D7993;
        position:absolute;
        margin-left: -10px;
        margin-top: -8px;
     }

     .parallax { 
    /* The image used */
    background-image: url("/static/images/learning.png");

    /* Set a specific height */
    height: 800px; 

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

 #ffd632

</style>
{% endblock %}

{% block body %}
<div id="content-container" style="position:relative;width:95%;height:1200px;z-index: -1; background-color:#D5D5D5;">
<div class="col-xs-1" style="margin-top:7%;padding:0">

<div class="row justify-content-md-center" style="max-height: ;position:relative;">

<img class="col-lg-9 col-md-auto" src='static/images/raised-hand-2.png' style="position:relative;height:74%;width:74%;padding:0;left:5px">

<div class="col-lg-3" style="margin-top:3%;z-index: 1;">
<h1>Our Goal</h1><p>The mission of Tutoring the Future is to give kids the opportunity they need to succeed in school and beyond. Students are the future and it is vital that we invest in that future. Tutoring the Future wants to provide students opportunities to develop essential skills that will help them succeed. Tutoring the Future wants to empower students to become the change they want to see in the world.</p> 
<a href="http://localhost:8000/about"><button type="button" style="position:relative;" class="btn btn-lg btn-outline-info">More...</button></a>
</div>

</div>
</div>

<!--<div style="margin-top:-45%;background: #D3D3D3;position: absolute;padding: 10px;opacity: 0.6;">-->
<div class="triangleRight"></div>
<h1 style="position:relative;font-size: 3.5em;top: 100px;left:65%;height:0px;width:100px" id="head1">Programs</h1>

<div id="content1" style="position:relative;top: 100px;height:0px;width:400px;color:white;z-index:1000">

<div id="tutoring">
<h3>Tutoring</h3>
<ul>
<li>Have help on your work with highschool students who had to go through the same thing.</li>
<li>Become ready to learn and absorb knowledge better at the next day at school.</li>
</ul>
<a href="http://localhost:8000/programs/#tutoring"><button type="button" style="position:relative;" class="btn bm btn-outline-info">Learn More</button></a>
</div>

<div id="debate" style="position:relative;left:70%;margin-top:-10%">
<h3>Debate</h3>
<ul>
<li>Develop public speaking skills</li>
<li>Learn how to develop and deliver an argument</li>
</ul>
<a href="http://localhost:8000/programs/#debate"><button type="button" style="position:relative;" class="btn bm btn-outline-info">Learn More</button></a>
</div>

<div id="programming" style="position:relative;left:150%;margin-top:-10%; width:500px;">
<h3>Programming</h3>
<ul>
<li>Learn the fundamentals and some more advanced topics in Java step by step with our teachers</li>
<li>After learning the Java we teach, we all will complete a real-world programming project together!</li>
</ul>
<a href="http://localhost:8000/programs/#programming"><button type="button" style="position:relative;" class="btn bm btn-outline-info">Learn More</button></a>
</div>

</div>

<div id="content2" style="position:relative;top:550px;z-index: 1000">
<h1 style="font-size: 3.5em;height:0">Join Us!</h1>
<p style="position:relative;height:0;z-index:1000;top:75px;width:50%;">Are you interested in becoming a tutor, debate teacher, or programming teacher at Tutoring the Future? Well, we're looking for highschool or college students who are knowledgebale and passionate in any of these fields. Does this description fit you? If it does, go and apply for the position and become part of the Tutoring the Future team. </p>
<a href="http://localhost:8000/team"><button type="button" style="position:absolute;top:250px" class="btn btnJoin btn-lg btn-outline-info">Learn more</button></a>
</div>

<div style="margin-top: -8px">

<div class="box1 parallax" style="height: 80%;margin-top:-23px;opacity: 1;z-index: -1"></div>
</div>

<div id="sep" style="margin-top: 55%;">
<div class="triangleLeft phonecomp" style="color: #D5D5D5;margin-top: -200px"></div>
<div class="box1" style="height:30%;margin-top:140px;background-color: #D5D5D5"></div>
</div>

<footer id="footer">
<div style="padding:10px;">
<div style="float:right;padding:20px 80px 0 0">
  <a href="http://localhost:8000">Home</a><br />
  <a href="http://localhost:8000/programs/">Programs</a><br />
  <a href="http://localhost:8000/team">Team</a><br />
  <a href="http://localhost:8000/about">About</a><br />
  <br /><br />
  <a href="#">Back to the Top</a>
</div>
  <p style="color: white">Contact us:<br />someone@example.com</p>
  <p style="color: white">Website designed and mantained by: Yuvraj Virk</p>
  <br />
  <p style="color: white">©tutoringthefuture.com. All rights reserved.</p>
</div>
</footer>

</div>
<!--<img class="img-responsive" src='static/images/LeoAcro.png' width="60%" height="80%" style="margin-left: 90%;">-->

{% endblock %}
{% block script %}
<script type="text/javascript">
if($(window).height()/$(window).width()<1){
	var el = $(".triangleLeft");
	var width=$(window).width();
	var w = ((width / 1.05) | 0); // calculate & trim decimals
	el.css("border-left-width", w + "px");

	var height=$(window).height()
	var h = ((height / 2) | 0); // calculate & trim decimals
	el.css("border-top-width", h + "px");	

	var el = $(".triangleRight");
	var width=$(window).width();
	var w = ((width / 1.05) | 0); // calculate & trim decimals
	el.css("border-right-width", w + "px");

	var height=$(window).height()
	var h = ((height / 2) | 0); // calculate & trim decimals
	el.css("border-bottom-width", h + "px");	
}else{
	var el = $(".triangleLeft");
	var width=$(window).width();
	var w = ((width / 1.05) | 0); // calculate & trim decimals
	el.css("border-left-width", w + "px");
	el.css("border-top-width", 100 + "px");	

	var el = $(".triangleRight");
	var width=$(window).width();
	var w = ((width / 1.05) | 0); // calculate & trim decimals
	el.css("border-right-width", w + "px");
	el.css("border-bottom-width", 100 + "px");	
}

if($(window).height()/$(window).width()>1){

	var el1 = $("#programming");
	el1.css("left","0px");
	el1.css("top","200px");	

	var el3=$("#debate");
	el3.css("left","0px")
	el3.css("top","100px");

	var el4=$("#sep");
	el4.css("margin-top","70%");

	var el5=$("#content1");
	el5.css("margin","0 auto");
	el5.css("width","100%");
	el5.css("top","100px");

	var el6=$("#content2");
	el6.css("top","700px");

	var el7=$(".btnJoin");
	el7.css("top","300px");

	var el8=$("#content-container");
	el8.css("height","120%");

	var el9=$("#footer");
	var h=$("#content-container").height();
	el9.css("top",h-150+"px");

	var el10=$("#head1");
	el10.css("top","0px");

	var el11=$(".phonecomp");
	el11.css("margin-top","40px");

	var el12=$(".parallax");
	el12.css("height","50%");

}else{
	var el9=$("#footer");
	var h=$("#content-container").height();
	el9.css("top",h+450+"px");
}


var ell= $(".box1");
var mar=$(".triangleLeft").css("border-top-width");
ell.css("margin-top", mar-200);

</script>
{% endblock %}

home/templates/student_signup.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style type="text/css">
.form-control{
  height:50px;
}
ul{
    list-style-type: none;
}
h1{
  margin-left: -20px;
  margin-top: 25%
}

</style>
{% endblock %}

{% block body %}
<div id="content-container" style="position:relative;top:15%;z-index:-1;width:95%;height:1850px;background-color: #DFDCE3
;">
<div class="container">
<div class="row">

<div class="col-lg-6">
<div class="col-lg-6" style="float:left;position: fixed;">
<h1>Ready to Learn? Yes! Well, let's get you signed up and started.</h1>
</div>
</div>

<div class="col-lg-6" style="float: right;">
<form method="POST">
{% csrf_token %}
<div class="form-group">
  {% for field in form %}
  {{ field.label_tag }}
    {% if forloop.counter == 9 %}
    (Ex:1234567890)
    {% endif %}
  <br>
    {{ field }}
    {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
    {% endfor %}
  {% endfor %}
</div>
  <button type="submit" class="btn btn-primary">Sign up</button>
</form>
</div>

</div>
</div>

<footer id="footer">
<div style="padding:10px;">
<div style="float:right;padding:20px 80px 0 0">
  <a href="http://localhost:8000">Home</a><br />
  <a href="http://localhost:8000/programs/">Programs</a><br />
  <a href="http://localhost:8000/team">Team</a><br />
  <a href="http://localhost:8000/about">About</a><br />
  <br /><br />
  <a href="#">Back to the Top</a>
</div>
  <p style="color: white">Contact us:<br />someone@example.com</p>
  <p style="color: white">Website designed and mantained by: Yuvraj Virk</p>
    <br />
  <p style="color: white">©tutoringthefuture.com. All rights reserved.</p>
</div>
</footer>

</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  if($(window).height()/$(window).width()>1){
    var elem= $('#extra');
    elem.css('display','none');

    var el9=$("#footer");
    var h=$("#content-container").height();
    el9.css("top",h-100+"px");
  }else{
    var el9=$("#footer");
    var h=$("#content-container").height();
    el9.css("top",h-400+"px");
  }
</script>
{% endblock %}

home/templates/teacher_signup.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<style type="text/css">
.form-control{
  height:50px;
}
ul{
    list-style-type: none;
}

#id_reason{
  height: 400px;
}
#id_qualifications{
  height:400px;
}
#id_methods{
  height:400px;
}
</style>
{% endblock %}

{% block body %}
<div id="content-container" style="position:relative;top:15%;z-index:-1;width:95%;height:3550px;background-color: #DFDCE3
;">
<div class="container">
<div class="row">

<div class="col-lg-6">
<div class="col-lg-6" style="float:left;position: fixed;">
<h1 style="margin-left: -20px;margin-top: 25%">Ready to Teach? Yes! Well, let's get you signed up and started.</h1>
</div>
</div>

<div class="col-lg-6" style="float: right;">
<form method="POST">
{% csrf_token %}
<div class="form-group">
  {% for field in form %}
  {{ field.label_tag }}
    {% if forloop.counter == 9 %}
    (Ex:1234567890)
    {% endif %}
  <br>
    {{ field }}
    {% for error in field.errors %}
      <p style="color: red">{{ error }}</p>
    {% endfor %}
  {% endfor %}
</div>
  <button type="submit" class="btn btn-primary">Sign up</button>
</form>
</div>

</div>
</div>

<footer id="footer">
<div style="padding:10px;">
<div style="float:right;padding:20px 80px 0 0">
  <a href="http://localhost:8000">Home</a><br />
  <a href="http://localhost:8000/programs/">Programs</a><br />
  <a href="http://localhost:8000/team">Team</a><br />
  <a href="http://localhost:8000/about">About</a><br />
  <br /><br />
  <a href="#">Back to the Top</a>
</div>
  <p style="color: white">Contact us:<br />someone@example.com</p>
  <p style="color: white">Website designed and mantained by: Yuvraj Virk</p>
    <br />
  <p style="color: white">©tutoringthefuture.com. All rights reserved.</p>
</div>
</footer>

</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  if($(window).height()/$(window).width()>1){
    var elem= $('#extra');
    elem.css('display','none');

    var el9=$("#footer");
    var h=$("#content-container").height();
    el9.css("top",h-100+"px");
  }else{
    var el9=$("#footer");
    var h=$("#content-container").height();
    el9.css("top",h-400+"px");
  }
</script>
{% endblock %}